spring:
  data:
    mongodb:
      authentication-database: admin
      username: admin
      password: admin
      database: task_db
      port: 27017
      host: localhost

security:
  userCredentials:
    - username: user01
      password: "{noop}password1"
    - username: user02
      password: "{noop}password2"
    - username: user03
      password: "{noop}password3"

